[package]
name = "image2ascii"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zune-core = "0.4.12"
zune-jpeg = "0.4.11"

[profile.dev.package.zune-jpeg]
opt-level = 3
